channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - pip
  - numpy
  - z5py=2.0.5
  - tensorflow=2.16.1
  - tensorflow-gpu=2.16.1
  - pip:
    - gputools
    - dask
    - edt
    - git+https://github.com/Neall37/stardist.git
